baseURL = 'https://zurdala.github.io/space-debris-confs/'
languageCode = 'en-us'
title = 'Conferences on Space Debris, SSA and STM'

theme = "hugo-bearblog"

[security]
  enableInlineShortcodes = true

[params]
lastUpdate = "2026-02-25T00:00:00"
githubURL = "https://github.com/zurdala/space-debris-confs"
githubURLIssue = "https://github.com/zurdala/space-debris-confs/issues/new?template=11-new-conference.md"